### ISSUE TITLE
Add an improper distribution class

### ISSUE THREAD

**Issue by AdrienCorenflos** [nchopin/particles#46]
A lot of SSMs start with a propagation step without any update. At the moment using particles for this is only feasible by a hack (e.g., Gaussian with very large noise). Adding an improper distribution that would always return 1/N as a result would (I think) result in the right algorithm (with no bias in the normalizing constant estimate) 

WDYT?

**Comment by nchopin** [comment]
You mean the distribution of Y_0 given X_0 should be improper, so that when you implement e.g. the bootstrap filter, at time 0 the weight function is constant? But then y_0 is simply discarded? That may create a few headaches: 

* The user should realize that, in that case, ``data[0]`` is ignored, and the actual data should be stored in ``data[1:]``. This behaviour is a bit surprising? 
* Such an improper distribution would not have a ``rvs`` method (since you can't simulate from an improper dist), but then the user may want to sample from the considered model, and using method ``StateSpaceModel.simulate`` will generate an error. 

Tbh, I like the "Gaussian with high variance" better, at least you know what you are doing. :-)

I'm going to close this issue, but I might re-consider if you and others manage to convince me.
