### ISSUE TITLE
Forum Creation

### ISSUE THREAD

**Issue by afcarzero1** [nchopin/particles#74]
I am very interested in this topic and I have been exploring the library in the past months in my free time. I find it hard to find people knowledgeable in the topic. Maybe a forum for questions might be created.

I am asking anyway my question here in the meantime:

As far as I understand all particle filters rely on the assumption that we have a model (even vague) of the underlying process. Has it ever been tried to learn the model directly from data and then apply the particle filters? I have a very complicated process with many observations and I think particle filters are the answer. But creating a model is basically imposible.

**Comment by nchopin** [comment]
hi,
there is a "discussions" thing on github, I could activate it if you want, that seems like a better place than "issues" (which is for tracking bugs).  

Regarding your question : as far as I know, there have been few attempts in this direction; one way to go would be to design a partly (or totally) nonparametric state-space models based on DPMs (Dirichlet Process mixtures); see this for instance :
https://arxiv.org/abs/1810.09291
or this (sorry, this is not on arxiv):
https://www.sciencedirect.com/science/article/pii/S0165168416000633?casa_token=xjtRJnI6BC0AAAAA:n4GqkbvamIrV853NBxA1SLYjOCCJ3sJ6_R0fTzZxWgxt7DK47wHrCOQEqQcamZGpmSC7W_wP4A

I am a bit sceptical about such approaches, because the estimation of *parametric* state-space models is already quite challenging; i.e. even with lot of data, some of your parameters may be hardly identified. So trying to use non-parametric model looks too ambitious. But there might be practical scenarios where it actually makes sense.

**Comment by nchopin** [comment]
Closing this since the OP did not reply, but happy to activate the discussions tab if anyone thinks it could be helpful.

**Comment by lukego** [comment]
> learn the model directly from data and then apply the particle filters?

I am also interested in this problem.

This paper might be interesting to you: https://arxiv.org/abs/2307.09607. They treat it as model selection by particle filtering over a large model space.
