### ISSUE TITLE
Is there a fast way to define a vector of parameters?

### ISSUE THREAD

**Issue by diolegend** [nchopin/particles#83]
Hello,

Is there a fast way to define a vector of parameters? 
Which are all Gamma distribution

prior_dict = {'lambda':dists.Gamma(), 'lambda1':dists.Gamma(), ...}
my_prior = dists.StructDist(prior_dict)

**Comment by diolegend** [comment]
```
class Model(ssm.StateSpaceModel):
    def PX0(self):  # Distribution of X_0
        return dists.MvNormal(loc=np.zeros(a_matrix_shape[0]), cov=np.eye(a_matrix_shape[0]))
    def PX(self, t, xp):  # Distribution of X_t given X_{t-1}=xp (p=past)
        u = np.zeros(paths)
        for i in range(paths):
            u[i] = np.random.poisson(getattr(self, keys[i]), 1)[0]
        return dists.MvNormal(loc=np.matmul(A_matrix, xp) + np.matmul(B_matrix, u), cov=(0.5*np.eye(a_matrix_shape[0])))
    def PY(self, t, xp, x):  # Distribution of Y_t given X_t=x (and possibly X_{t-1}=xp)
        return dists.MvNormal(loc=np.matmul(H_matrix, x), cov=(0.5*np.eye(h_matrix_shape[0])))
```
The state space model is
![Screenshot 2024-04-20 011328](https://github.com/nchopin/particles/assets/18214809/e386ae25-8287-44e7-9047-f1f0fe237907)

I'm dealing with a multidimensional vector of x which is a vector of dimension 456, and y is a vector of dimension 19.
So H matrix must be 19x456, A is a matrix of 456x456, B is a matrix of 456x24, and u is a vector of 24.

I can't let it work, because if I pass nx=200, I get a x with dimension (200,456) that will break my np.matmul(H_matrix, x).

How can I let it work to return all my 24 lambdas posteriors in the right way?

**Comment by nchopin** [comment]
> Hello,
> 
> Is there a fast way to define a vector of parameters? Which are all Gamma distribution
> 
> prior_dict = {'lambda':dists.Gamma(), 'lambda1':dists.Gamma(), ...} my_prior = dists.StructDist(prior_dict)

You can use IndepProd to define a multivariate distribution with independent components:
<https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/_autosummary/particles.distributions.IndepProd.html#particles.distributions.IndepProd>

For instance in your case you can do:

```
from particles import distributions as dists

several_gammas = [dists.Gamma(a=2., b=2.) for _ in range(10)]
indep_gamma_dist = dists.IndepProd(*several_gammas)
x = indep_gamma_dist.rvs(size=20)  # will generate a (20, 10) array
```

**Comment by nchopin** [comment]
For your second question, please post a MWE:
<https://en.wikipedia.org/wiki/Minimal_reproducible_example>

**Comment by diolegend** [comment]
Hello @nchopin 
This is the MWE:
https://github.com/williamzhao1999/minimal_test

**Comment by nchopin** [comment]
Ok, I think there are several issues with your code, but the main one is this line:

```
def PY(self, t, xp, x): 
    return dists.MvNormal(loc=np.matmul(H_matrix, x), cov=(0.5*np.eye(h_matrix_shape[0])))
```

The object `x` is (usually) a numpy array of shape (N, dx), where N is the number of particles, and dx is the dimension of the state-space. You have to rewrite your code so that it does the proper linear algebra operation, i.e. something like `x @ H_matrix.T` (please double check). 

Other points:
* I find it confusing that you would set parameter `Nx` (number of particles in the x-dimension) to the same number as the dimension of x, this does not seem right. 
* You should really check first that the bootstrap filter works reasonably well for your model (for a fixed set of parameters). Given the high dimension of $X_t$, I'm pretty sure that the bootstrap filter will work poorly, and in return PMMH cannot work well either. 

Hope this helps.

**Comment by williamzhao1999** [comment]
Thank you very much, it absolutely help, 

yes sorry for let you confusing, I was just figuring out a solution so I set nx=456, as I remember in theory, the particles can be in arbitrary number, large is preferred.

I'm just trying to replicate this paper https://ieeexplore.ieee.org/document/8917143

They are estimated the lambdas (parameter of Poisson) using this state space model for Particle Metropolis Hastings.

I will retry the program once I am at home.

**Comment by diolegend** [comment]
if i set Nx=1000,
In the PX function, i changed to

 `return dists.MvNormal(loc=xp @ A_matrix.T + np.matmul(B_matrix, u), cov=(0.5*np.eye(a_matrix_shape[0]))) `

is it correct?

**Comment by diolegend** [comment]
![particles](https://github.com/nchopin/particles/assets/18214809/3358a8dc-cbea-4cec-8de3-7149148078c0)
Why other particles has the same value after the first particle? 
This is the xp

**Comment by diolegend** [comment]
Thank you very much!, I thought you wouldn't answer me anymore.

I updated the repo, you can check it
https://github.com/williamzhao1999/minimal_test

**Comment by nchopin** [comment]
Well, it's simple really: the bootstrap filter works very poorly for your model (as I suggested it might a few posts back), in particular the ESS drops to 1 at each iteration, because the variance of the weights is so high. This implies that only one particle gets a non-negligible weight, and this particle is always selected by the resampling step. This is why you get N times the same particle in array `xp`, which is actually the array of $X_{t-1}^{A_t^n}$, i.e. the array of the N resampled particles. 

The model you are considering is such that $X_t$ is of very high-dimension, in such a case the bootstrap filter will never work unless you take N very, very large. This is a mathematical issue, not an issue with the code. 

Possible solutions:
* consider a much simpler (smaller) model ;
* try to design a guided filter (i.e. a particle filter with a better proposal than the standard one used in the bootstrap filter).

**Comment by nchopin** [comment]
From this screenshot, I can see they use a particular proposal $q$ (first line inside the loop), but you'll have to read the paper to see which one they are using.

**Comment by williamzhao1999** [comment]
They didn't say in the paper what is the initial proposal distribution, but they say how to update.

So having the proposal distribution, the algorithm is feasible?

![image](https://github.com/nchopin/particles/assets/72149698/8fe38483-a3b5-4445-8dab-e319f2c227cd)

**Comment by nchopin** [comment]
This place is for tracking issue with the software, not answering general math questions.

**Comment by diolegend** [comment]
Sorry
