### ISSUE TITLE
Customizing MH Kernel for SMC in Binary Parameter Spaces

### ISSUE THREAD

**Issue by eekom-research** [nchopin/particles#90]
Hi Professor @nchopin and other contributors,

I am currently working on Bayesian inference using Sequential Monte Carlo (SMC) with tempering, specifically focusing on binary parameter spaces. The approach is similar to "Sequential Monte Carlo on large binary sampling spaces" by Christian Schäfer and Nicolas Chopin (Statistics and Computing 23, 2013: 163-184).

I have several questions regarding the customization of the Metropolis-Hastings (MH) Kernel for the move step in this context:

1. Is it feasible to specify a conditional binary distribution for the proposal within the MH Kernel?
2. Can the parameters of the aforementioned proposal distribution be updated or adapted using the particles from the previous stage?
3. Is it possible for the proposal to be sampled via Gibbs sampling, starting from the current sample in the particles?

I would appreciate any guidance that could assist in implementing these features effectively with the module

**Comment by nchopin** [comment]
hi, 
Yes, it's completely possible to implement any MCMC kernel, whether Gibbs (your point 3) or Metropolis (your point 1), using the current sample (your point 2). To do so, you may take inspiration from BinaryMetropolis, see here <https://github.com/nchopin/particles/blob/b9dbaa8194b4661b32b06a75a6333904a77769e0/particles/binary_smc.py#L158>, or its parent class, state_space_models.ArrayMetropolis.
Basically, what these classes do is to take as input an array representing N particles, and generates a new array of N particles, that correspond to applying N times the same MCMC kernel. One method of these classes is calibrate, and what it does is to calibrate the tuning parameters of your kernel based on the current particle sample.   
Please have a look at these classes and their documentation. If you have questions, let me know, but since I'm currently on family holiday, I might need time to get back to you.

**Comment by eekom-research** [comment]
> hi, Yes, it's completely possible to implement any MCMC kernel, whether Gibbs (your point 3) or Metropolis (your point 1), using the current sample (your point 2). To do so, you may take inspiration from BinaryMetropolis, see here
> 
> https://github.com/nchopin/particles/blob/b9dbaa8194b4661b32b06a75a6333904a77769e0/particles/binary_smc.py#L158
> 
> , or its parent class, state_space_models.ArrayMetropolis.
> Basically, what these classes do is to take as input an array representing N particles, and generates a new array of N particles, that correspond to applying N times the same MCMC kernel. One method of these classes is calibrate, and what it does is to calibrate the tuning parameters of your kernel based on the current particle sample.
> Please have a look at these classes and their documentation. If you have questions, let me know, but since I'm currently on family holiday, I might need time to get back to you.

Thank you. This seems like exactly what I need. I would take a look at the documentation.

**Comment by eekom-research** [comment]
Hi Professor @nchopin,

What is the best way to send information to an MCMC kernel? Should this be accomplished by using an additional entry in 'X.shared`? For example, I want to pass a set of fixed coefficient values (constant for all Metropolis steps), which define the prior distributions, to the `calibrate`  method of my MCMC kernel.

**Comment by nchopin** [comment]
Hi,
are these "fixed" coefficients fixed from the start (i.e. not set according to the particle sample, at each time t)? In this case, you could simply treat them as attributes of the class that define your MCMC kernel, and set these attributes when you instantiate the class? 
But otherwise, yes, `X.shared` is a dictionary that you can use to store any estimate computed from the particle sample. These estimates should be computed by method `calibrate` (this method is called at each iteration t, after the particles are generated and their weights are computed). For instance, for random walk Metropolis, method `calibrate` computes the covariance matrix of the weighted particle sample, and saved it in `X.shared`; then the method that actually generates the N new particles uses it to sample from the proposal (a Gaussian with the same cov matrix, multiplied by a scalar). 
Let me know if this is not clear? 
I should really improve the documentation regarding how MCMC kernels work, and in particular what is `X.shared`. I'm going to mark this issue as "enhancement" to remind me to do so when I'm back.

**Comment by eekom-research** [comment]
> Hi, are these "fixed" coefficients fixed from the start (i.e. not set according to the particle sample, at each time t)? In this case, you could simply treat them as attributes of the class that define your MCMC kernel, and set these attributes when you instantiate the class? But otherwise, yes, `X.shared` is a dictionary that you can use to store any estimate computed from the particle sample. These estimates should be computed by method `calibrate` (this method is called at each iteration t, after the particles are generated and their weights are computed). For instance, for random walk Metropolis, method `calibrate` computes the covariance matrix of the weighted particle sample, and saved it in `X.shared`; then the method that actually generates the N new particles uses it to sample from the proposal (a Gaussian with the same cov matrix, multiplied by a scalar). Let me know if this is not clear? I should really improve the documentation regarding how MCMC kernels work, and in particular what is `X.shared`. I'm going to mark this issue as "enhancement" to remind me to do so when I'm back.

Thank you, Professor @nchopin, for the clear explanation.

I have a follow-up question regarding the tempering algorithm. Is there a storage and lookup mechanism within the algorithm that minimizes repeated evaluations of the forward model embedded in the likelihood function, especially when the same parameters are used across different stages of the algorithm? For example, in my simulations, evaluating the likelihood of my model for a given parameter realization requires running a computationally expensive forward model. However, different values of $\gamma_t$ for the same parameter realization do not necessitate a new evaluation of the forward model. I am curious if there is any built-in functionality in the algorithm to handle such cases.

**Comment by nchopin** [comment]
The implementation makes sure you don't evaluate the likelihood function more than once for each (considered) parameter value. Basically, when a given parameter value `theta` is generated, its (log-)likelihood is computed immediately, and then stored in array `X.llik`.

**Comment by eekom-research** [comment]
Hello Professor @nchopin,

Thanks for your your assistance and clarification does far. I am happy to say I have been able to implement my model using your excellent particles package. On a related note, do you have any published/related work on combining multi-level Monte Carlo methods with the adaptive tempering SMC sampler? This would be useful, for example, in reducing the cost of problems with expensive forward model computations

**Comment by nchopin** [comment]
Maybe check AJay Jasra's publication list, he and his-co-authors wrote several papers on how to combine SMC with multi-level Monte Carlo:
https://sites.google.com/site/ajayjasra0/home

**Comment by nchopin** [comment]
Closing this and opening a new issue to remind me to improve documentation regarding MCMC kernels.
